# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

#Your build pipeline references an undefined variable named ‘Parameters.DevOpsPat’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

name: $(Date:yy)$(DayOfYear)$(rev:.r)
steps: 

- script: echo hello BuildNumber $(Build.BuildNumber)
  displayName: 'BuildNumber'

- script: dotnet restore ./src/IdentityServer4-Extension-Grants.sln
  displayName: 'dotnet restore'

- script: dotnet build --configuration $(buildConfiguration) ./src/IdentityServer4-Extension-Grants.sln
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet test ./src/IdentityServer4-Extension-Grants.sln --logger trx --collect "Code coverage"
  displayName: 'dotnet test'

- script: dotnet pack --configuration $(buildConfiguration) --no-build ./src/IdentityServer4-Extension-Grants.sln
  displayName: 'dotnet pack'

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'


